pass options to prepend-http
sindresorhus/url-parse-lax pull request #1
Opened 2017-10-06 14:50 UTC by gillesdemey

Allows passing options to `prepend-http` to allow the HTTPS protocol to be set by default.

2017-10-06 15:54 UTC, SamVerschueren requested changes
Can you add docs and a test?

2017-10-06 15:55 UTC, gillesdemey commented
Will get on that :)

2017-10-07 17:42 UTC, gillesdemey commented
It seems that Travis tests run on an ancient version of Node and complains about ES6 syntax, thoughts on how to proceed?

2017-10-07 18:16 UTC, SamVerschueren commented
Added a PR to drop support for ancient Node versions. So let's wait until Sindre reviewed and merged that one. Will make things easier :).

2017-10-07 20:19 UTC, gillesdemey commented
rebased from master, PTAL :)

2017-10-08 04:45 UTC, SamVerschueren requested changes
I added an API section, can you add it there as well in the same fashion as https://github.com/sindresorhus/prepend-http#prependhttpurl-options.

2017-10-08 10:51 UTC, gillesdemey commented
Ah I missed that, added it to the API section with a link to `prepend-http`, or should we copy over the documentation instead?

2017-10-08 11:51 UTC, SamVerschueren commented
> or should we copy over the documentation instead?

I'm ok with what we have now. I'll let @sindresorhus decide :).

Thanks for the PR!

2017-10-08 11:51 UTC, SamVerschueren approved these changes

2017-10-17 10:15 UTC, merged